name = "PaperUnfittedFEMDarcy"
uuid = "42403660-79e6-4b07-bca3-d17f89a42e18"
authors = ["Santiago Badia <santiago.badia@monash.edu>", "Anne Boschman <anne.boschman@monash.edu>", "Alberto F. Martin <alberto.f.martin@anu.edu.au>", "Erik Nilsson <erik.nilsson@umontpellier.fr>", "Ricardo Ruiz-Baier <ricardo.ruizbaier@monash.edu>", "Sara Zahedi <sara.zahedi@math.kth.se>"]
version = "0.0.1"

[deps]
Gridap = "56d4f2e9-7ea1-5844-9cf6-b9c51ca7ce8e"
GridapEmbedded = "8838a6a3-0006-4405-b874-385995508d5d"
GridapPETSc = "bcdc36c2-0c3e-11ea-095a-c9dadae499f1"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
Printf = "de0858da-6303-5e67-8744-51eddeeeb8d7"

[compat]
Gridap = "=0.19.3" 
GridapEmbedded = "=0.9.8"
GridapPETSc = "=0.5.6"
julia = "1.9, 1.10"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
